version: '2'
services:
  node:
    build: 
      context: .
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network
    environment:
      - MONGO_URL=mongodb
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo
    networks:
      - nodeapp-network
    ports:
      - "27017:27017"
networks:
  nodeapp-network:
    driver: bridge

